/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Radiant Software (64-bit)
    2.2.1.239.2
    Soft IP Version: 1.0.1
    2021 05 19 00:34:25
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module PLL_DEV_48M (ref_clk_i, rst_n_i, bypass_i, lock_o, outcore_o,
    outglobal_o)/* synthesis syn_black_box syn_declare_black_box=1 */;
    input  ref_clk_i;
    input  rst_n_i;
    input  bypass_i;
    output  lock_o;
    output  outcore_o;
    output  outglobal_o;
endmodule